name: Perforce Klocwork scan

on:
  push:
    branches:
     - main

permissions:
  id-token: write
  contents: read

jobs:
  klocwork-codescan:
    runs-on:
     ubuntu-latest
    outputs:
      klocwork-job-output-critical: ${{ steps.klocwork-step.outputs.critical-count }}
      klocwork-job-output-very-high: ${{ steps.klocwork-step.outputs.very-high-count }}
      klocwork-job-output-high: ${{ steps.klocwork-step.outputs.high-count }}
      klocwork-job-output-medium: ${{ steps.klocwork-step.outputs.medium-count }}
      klocwork-job-output-low: ${{ steps.klocwork-step.outputs.low-count }}
    steps:

      # Checkout code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Print run info
      - name: Print run info
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"

      # Run Klocwork scan
      - name: Klocwork scan
        id: klocwork-step
        uses: cloudbees-io-gha/perforce-klocwork-sast-publish@v1
        with:
          cloudbees-url: ${{ vars.CLOUDBEES_QA_API_URL }}
          url: ${{ vars.KLOCWORK_URL }}
          token: ${{ secrets.KLOCWORK_APP_TOKEN }}
          license-host: ${{ vars.KLOCWORK_LICENSE }}
          username: ${{ vars.KLOCWORK_USERNAME }}
          project-name: test-java-project
          build-directory: app
          build-tool: maven
          enable-agent-scan: false
          enable-local-scan: true

      - name: Source dir examine
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" -w /work golang:1.20.3-alpine3.17 ls -latR /work

      - id: print-outputs-from-klocwork-step
        name: Print outputs from the upstream Perforce Klocwork Scan step
        run: |
          # Printing all outputs
          echo "Outputs from upstream Perforce Klocwork Scan step:"
          echo "Critical count: ${{ steps.klocwork-step.outputs.critical-count }}"
          echo "Very high count: ${{ steps.klocwork-step.outputs.very-high-count }}"
          echo "High count: ${{ steps.klocwork-step.outputs.high-count }}"
          echo "Medium count: ${{ steps.klocwork-step.outputs.medium-count }}"
          echo "Low count: ${{ steps.klocwork-step.outputs.low-count }}"
